name: hanscnc-monitor

on:
  schedule:
    - cron: "*/5 1-10 * * 1-5"   # 工作日(CST 09:00–18:00)每5分钟
    - cron: "0 */2 * * *"        # 其他时段每2小时
  workflow_dispatch:
    inputs:
      force_notify:
        description: "立即测试通知（不改状态）"
        required: false
        default: "false"

permissions:
  contents: write

concurrency:
  group: hanscnc-monitor
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run monitor
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
          FORCE_NOTIFY: ${{ inputs.force_notify }}
        run: |
          python monitor.py
      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update monitor state [skip ci]"
            git push
          fi
